export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const CLEAR_SERVICE_FIELD = 'CLEAR_SERVICE_FIELD';
export const CANCEL_EDIT_STATE = 'CANCEL_EDIT_STATE';
export const BEGIN_EDIT = 'BEGIN_EDIT';
export const EDIT_ITEM = 'EDITING';
